name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
#     runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: tpick-vn/tpick-actions/keyvault@v1
