name: Test

on:
  workflow_dispatch:
    inputs:
      input-a:
        description: 'Input a'     
        required: true
        default: 'A' 
        type: choice
        options:
        - A
        - B
        - C 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
#     runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: tpick-vn/tpick-actions/keyvault@v1
