name: Test

on:
  workflow_dispatch:
    inputs:
      input-a:
        description: 'Input a'     
        required: true
        default: 'A' 
        type: choice
        options:
        - A
        - B
        - C 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: tpick-vn/tpick-actions/docker@v1
        with: 
          image-name: tpick-core
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

